repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: check-json
        files: \.json$
      - id: pretty-format-json
        files: \.json$
        args: ["--autofix"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(yaml|yml|json)$
        args: [--write]

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        name: Format TOML files
        files: \.toml$
        args: [--verbose, --diff]
      - id: taplo-lint
        name: Lint TOML files
        files: \.toml$
        args: [--verbose]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      # Run the linter.
      - id: ruff-check
        files: \.py$
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        files: \.py$
