# Taplo configuration for TOML formatting and validation
# See: https://taplo.tamasfe.dev/configuration/file.html

include = [ "**/*.toml" ]

[formatting]
    align_entries         = true
    align_comments        = true
    array_trailing_comma  = true
    array_auto_expand     = true
    array_auto_collapse   = true
    compact_arrays        = false
    compact_inline_tables = true
    inline_table_expand   = true
    compact_entries       = false
    column_width          = 100
    indent_tables         = true
    indent_entries        = true
    indent_string         = "    "
    trailing_newline      = true
    reorder_keys          = false
    reorder_arrays        = true
    reorder_inline_tables = true
    allowed_blank_lines   = 2
    crlf                  = false

[[rule]]
    include = [ "**/pyproject.toml", "pyproject.toml" ]

    [rule.schema]
        path    = "https://json.schemastore.org/pyproject.json"
        enabled = true
