name: Pre-commit checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Install pre-commit
        run: |
          uv add --dev pre-commit

      - name: run precommit
        run: |
          echo "Running pre-commit on all files..."
          uv run pre-commit run --show-diff-on-failure --verbose --all-files
