name: Test Taplo Formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-taplo:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install pre-commit
      run: pip install pre-commit
    
    - name: Run taplo formatting
      run: pre-commit run taplo-format --all-files --verbose
      
    - name: Show git diff if formatting failed
      if: failure()
      run: |
        echo "Git status:"
        git status
        echo "Git diff:"
        git diff
